spring:
  data:
    mongodb:
      database: crud
      port: 27017
      host: cluster0.znco0.mongodb.net
      password: tIHppntOopTSh2tA
      username: camarar
#      uri: mongodb://camarar:tIHppntOopTSh2tA@cluster0.znco0.mongodb.net/crud
      repositories:
        enabled: true
#  datasource:
#    password: tIHppntOopTSh2tA
#    username: camarar
#    url: jdbc:mongodb://cluster0.znco0.mongodb.net/crud
#    driver-class-name: com.mysqcom.dbschema.MongoDbJdbcDriver
  jpa:
    hibernate:
      ddl-auto: update
