spring:
  data:
    mongodb:
      password: tIHppntOopTSh2tA
      username: camarar
      uri: mongodb://cluster0.znco0.mongodb.net/crud
#  datasource:
#    password: tIHppntOopTSh2tA
#    username: camarar
#    url: jdbc:mongodb://cluster0.znco0.mongodb.net/crud
#    driver-class-name: com.mysqcom.dbschema.MongoDbJdbcDriver
  jpa:
    hibernate:
      ddl-auto: update
